# Generated by Django 3.2.10 on 2021-12-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='prenom',
        ),
    ]
